### ISSUE TITLE
Eliminar inglés

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalDay#10]
Personalmente me cargaría el link para ver la web en inglés.

Un Dday no tiene público inglés y ni perri va a venir a Cáceres a un Dday desde fuera de España (Maybe, alguno de Portugal pero entienden Español escrito sin problemas), mantener el idioma implica crear los contenidos dos veces y no aporta valor alguno.

**Comment by keopx** [comment]
@samuelsolis la cierro yo no veo ingles dispionible

cc @alvar0hurtad0
