### ISSUE TITLE
Quitar el botón de "Registrarse" si estás logueado

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalDay#11]
O cambiarle el texto a editar mi perfil, pero no creo que tenga sentido dejarlo.

**Comment by keopx** [comment]
@samuelsolis lo he hecho es que ese bloque solo este disponible para usuarios anonimos.

cc @alvar0hurtad0

**Comment by alvar0hurtad0** [comment]
10x

2017-07-23 11:49 GMT+02:00 keopx <notifications@github.com>:
