### ISSUE TITLE
Call4Papers: Activar y desactivar la acción

### ISSUE THREAD

**Issue by keopx** [AsociacionDrupalES/DrupalDay#13]
El call4papers funciona de la siguiente manera:

- Los usuarios tienen que estar registrados
- El tipo de contenido sesión puede ser creado por usuarios autenticados.
  - Algunos campos no pueden editar los usuarios. El estado solo los admin pueden modificarlos.
    - Modulo: field_permission
    - Feature: content_sesion
    - Bloque: Drupal day link to Submit Session
- Una vez el _call4papers_ se cierra se quita dicho permiso de creación/edición de sesiones y se activa el la feature _content_sesion_ y genera una vista con las sesiones aprobadas.
- Luego los admin cambian el estado a _Aceptada_ a las sesiones que se han sido seleccionadas y listo.

Si no queda claro hacemos una llamada.

Ayudas: 
- Ver feature: https://2017.drupalday.es/admin/structure/features/content_sesion
- Bloque: Drupal day link to Submit Session

__NOTA: La feature lo que hace es ponerlo en modo call4papers cerrado, por tanto es necesario deshacer lo que dice la features__

**Comment by keopx** [comment]
Si alguien tiene dudas con esta feature, que me comente, sino que me diga y realizo los pasos necesarios para activar el call4papers :)

**Comment by DavidHernandez** [comment]
El C4P ya esta habilitado. Podemos cerrar esto?

**Comment by keopx** [comment]
Claro @DavidHernandez
