### ISSUE TITLE
Añadir más información sobre "cómo llegar"

### ISSUE THREAD

**Issue by keopx** [AsociacionDrupalES/DrupalDay#16]
Añadir más información sobre "cómo llegar"

**Comment by keopx** [comment]
Esta esta hecho verdad? podemos cerrarla @alvar0hurtad0

**Comment by rbordallo** [comment]
Hola,

Idem, añado alguna cosilla más este finde.

**Comment by rbordallo** [comment]
Actualizada la información de la página Cómo llegar.

**Comment by keopx** [comment]
@rbordallo gracias, la cierro 
cc @alvar0hurtad0
