### ISSUE TITLE
Añadir más información sobre hoteles. De momento solo se ha eliminado lo de Bilbao y añadido uno de prueba.

### ISSUE THREAD

**Issue by keopx** [AsociacionDrupalES/DrupalDay#17]
Añadir más información sobre hoteles. De momento solo se ha eliminado lo de Bilbao y añadido uno de prueba.

**Comment by keopx** [comment]
@alvar0hurtad0 esto ya lo has hecho por lo que veo, se puede cerrar?

**Comment by rbordallo** [comment]
Hola,

Tengo algo de info adicional. Este finde lo añado.

**Comment by keopx** [comment]
@rbordallo yo veo varios: https://2017.drupalday.es/pagina/alojamiento

**Comment by samuelsolis** [comment]
Sí, metí yo los que me pareció. Para mí está pero si queréis meter más sois
libres.

También creé un mapa monoso se locales :)

**Comment by keopx** [comment]
@samuelsolis muchas gracias.
@samuelsolis  @rbordallo la cierro. Si eso ya se hará pero vamos a ir cerrando las cosas.

cc @alvar0hurtad0

**Comment by rbordallo** [comment]
Buenas tardes!

Hecho. He añadido 2 hoteles y varios apartamentos turísticos.



2017-07-30 11:59 GMT+02:00 keopx <notifications@github.com>:

**Comment by keopx** [comment]
Genial @rbordallo
