### ISSUE TITLE
Menu en 2 lineas

### ISSUE THREAD

**Issue by Willeaton** [AsociacionDrupalES/DrupalDay#19]
El menu sale en dos lineas

**Comment by keopx** [comment]
@Willeaton no puedo reproducirlo.

Puedes añadir un screeshot y version del navegador :+1:

**Comment by Willeaton** [comment]
![drupal day](https://user-images.githubusercontent.com/28909500/29132932-1a2945c0-7d32-11e7-940a-bf581e038008.png)
He seleccionado todo el texto para que lo veas, en el trabajo veo dos enlaces en segunda linea, en casa solo una. En ambos casos estoy usando Chrome en Windows. Quizas una diferencia por un tipo de letra aplicada entre los SO diferentes

**Comment by Willeaton** [comment]
Con este cambio se arregla en mi pantalla...

@media (min-width: 61.2em)
styles.css?ouey4q:783
ul.nice-menu a {
    padding: 0.3em 1.7em 0.1em;
}

**Comment by keopx** [comment]
@alvar0hurtad0 puedes meter esto y compilar el sass porfa

**Comment by alvar0hurtad0** [comment]
de esto se está encargando Jorge.

2017-08-24 19:57 GMT+02:00 keopx <notifications@github.com>:

**Comment by keopx** [comment]
Gracias @Jorgillo!!!

CC @Willeaton @alvar0hurtad0
