### ISSUE TITLE
Logo flash on load

### ISSUE THREAD

**Issue by Willeaton** [AsociacionDrupalES/DrupalDay#21]
Cuando cargas la pagina el logo sale grande luego reduce. Quizas un trozo de css inline puede ayudar?

**Comment by keopx** [comment]
@Willeaton mmm he visto el efecto alguna vez, pocas la verdad. ¿Merece la pena dedicar tiempo a esto?

**Comment by samuelsolis** [comment]
Es bastante coñazo y es un fix fácil. Si una de estas pillo la BD de esto lo subo. Básicamente es añadir esa línea de CSS a un style inline en el body. 

https://css-tricks.com/authoring-critical-fold-css/
