### ISSUE TITLE
Crear una lista de correo drupalday@drupal.es o en el caso de que exista cambiar los correos de los organizadores.

### ISSUE THREAD

**Issue by alvar0hurtad0** [AsociacionDrupalES/DrupalDay#7]

**Comment by keopx** [comment]
¿Cual es el caso de uso?

**Comment by alvar0hurtad0** [comment]
el caso de uso es que sé que las notificaciones de esto si llegan.

Y lo necesitamos para el contacto.

2017-07-16 10:01 GMT+02:00 keopx <notifications@github.com>:

> ¿Cual es el caso de uso?
>
> El 16 jul. 2017 9:29 a. m., "Alvaro J. Hurtado Villegas" <

**Comment by capynet** [comment]
Cuenta creada. La clave la tienen todos los integrantes de la junta de la AED
