### ISSUE TITLE
Poner la fecha del evento y el lugar en la cabecera

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalDay#9]
Como sea y donde sea, pero en la cabecera. Con una imagen con toda la info debería valer.

**Comment by keopx** [comment]
@alvar0hurtad0 @samuelsolis 

He creado los sliders con imágenes del ayuntamiento y de la sección de turismo. Revisad textos etc.

Espero que la selección al menos haya sido decente :)

**Comment by DavidHernandez** [comment]
Supongo que esto ya se puede cerrar:

![screenshot from 2017-08-09 14-41-46](https://user-images.githubusercontent.com/877002/29121940-e83eca6a-7d10-11e7-9e5e-4c62f88462e5.png)

**Comment by keopx** [comment]
@DavidHernandez correcto.
Cierro
